name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
