name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron:  "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - name: Set up Python
          # This is the version of the action for setting up Python, not the Python version.
          uses: actions/setup-python@v5
          with:
          # Semantic version range syntax or exact version of a Python version
            python-version: '3.x'
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        - name: Install libturbojpeg
          run: sudo apt-get install -y libturbojpeg
        - uses: "actions/checkout@main"
        - uses: "home-assistant/actions/hassfest@master"
